import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono, Space_Grotesk, Poppins } from 'next/font/google'
import '../globals.css'
import { SidebarProvider } from "@/components/ui/sidebar"
import  AppSidebar from "@/components/app-sidebar"
import Navbar from '@/components/Navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
})

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider afterSignInUrl='/work' afterSignUpUrl='/work'>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${poppins.className}`}>
        <body className="flex">
          <SidebarProvider>
            <AppSidebar />
            <div className="flex flex-col flex-1 min-h-screen">
                 {/* <Navbar/> */}
              <main className="p-4 flex-1">
             
                {children}</main>
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
